name: Mokotest
version: 0.0.1

httpConf:
  host: 127.0.0.1
  port: 8080

dbConf:
  dsn: root:1amnohero@tcp(localhost:3306)/learnecho?parseTime=true
  dsnTesst: root:1amnohero@tcp(localhost:3306)/learnechotest?parseTime=true
  maxOpenConns: 5
  maxIdleConns: 5
  maxIdleTime: 100
  dialect: mysql

emailConf:
  email: altacapstonegroup3@gmail.com
  password: ppvxpgjmyirnqmdm
  host: smtp.gmail.com
  port: 587
